version: "3"

services:
  web:
    # build: .
    image: na2na/misskey-na2na:release
    restart: always
    links:
      - redis
      # - db
      # - es
    ports:
      - "3000:3000"
    networks:
      - internal_network
      - external_network
    volumes:
      - ./files:/misskey/files
      - ./.config:/misskey/.config:ro

  # db:
  #   restart: always
  #   image: postgres:14.5-bullseye
  #   networks:
  #     - internal_network
  #   env_file:
  #     - .config/docker.env
  #   volumes:
  #     - ./db:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:7.0.5-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data
  # es:
  #   restart: always
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "TAKE_FILE_OWNERSHIP=111"
  #     - discovery.type=single-node
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   networks:
  #     - internal_network
  #   env_file:
  #     - .config/docker.env
  #   volumes:
  #     - ./elasticsearch:/usr/share/elasticsearch/data

networks:
  internal_network:
    internal: true
  external_network:
