image:
  repository: na2na/misskey-na2na
  tag: "2024.5.0-na2na-v2"
  pullPolicy: Always

database:
  host: "hoge.local"
  port: 5432
  db: "misskey"
  user: "misskey"
  pass: "misskey"

redis:
  host: "localhost"
  port: 6379

service:
  host: "https://mk8stest.na2na.dev/"
  type: NodePort
  port: 3000
  nodePort: 30000

nodeSelector: {}

tolerations: []

affinity: {}

# HPAの設定
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

resources:
  requests:
    cpu: 100m
    memory: 1500Mi
  limits:
    cpu: 350m
    memory: 2Gi

livenessProbe:
  initialDelaySeconds: 80
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 80
