image:
  web:
    repository: na2na/misskey-na2na
    tag: "2024.5.0-na2na-v3"
    pullPolicy: IfNotPresent
    strategy: RollingUpdate

misskeyCm:
  hostUrl: "https://mk8stest.na2na.dev/"
  database:
    host: "hoge.local"
    port: 5432
    db: "misskey"
    user: "misskey"
    pass: "misskey"
  redis:
    host: "localhost"
    port: 6379
  misskeyBlockMentionsFromUnfamiliarRemoteUsers: false

service:
  type: ClusterIP
  port: 3000

nodeSelector: {}

tolerations: []

affinity: {}

pdb:
  enabled: true
  minAvailable: 1
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

resources:
  requests:
    cpu: 200m
    memory: 1500Mi
  limits:
    cpu: 450m
    memory: 2Gi

livenessProbe:
  initialDelaySeconds: 80
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 80
