image:
  web:
    repository: na2na/misskey-na2na
    tag: "2024.5.0-na2na-v3"
    pullPolicy: IfNotPresent
    strategy: RollingUpdate
  descheduler:
    repository: registry.k8s.io/descheduler/descheduler
    tag: v0.30.1

misskeyCm:
  hostUrl: "https://mk8stest.na2na.dev/"
  database:
    host: ""
    port: 5432
    db: ""
    user: ""
    pass: ""
  redis:
    host: "localhost"
    port: 6379
  misskeyBlockMentionsFromUnfamiliarRemoteUsers: false

service:
  type: ClusterIP
  port: 3000

nodeSelector: {}

tolerations: []

affinity: {}

pdb:
  enabled: true
  minAvailable: 1
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 85
resources:
  requests:
    cpu: 200m
    memory: 1500Mi
  limits:
    cpu: 450m
    memory: 2Gi
livenessProbe:
  initialDelaySeconds: 80
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 80

descheduler:
  enabled: true
  maxPodLifeTimeSeconds: 86400
  schedule: "0 */6 * * *"

externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore
  targetName: misskey-external-secret
  creationPolicy: Owner
  remoteRef:
    databaseHostKey: ""
    databasePasswordKey: ""
