{{ if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "web.fullname" . }}-external-secret
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
  target:
    name: {{ include "web.fullname" . }}-external-secret
    creationPolicy: {{ .Values.externalSecrets.creationPolicy }}
  data:
    - secretKey: DATABASE_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.databaseHostKey }}
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.databasePasswordKey }}
{{ end }}
