apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  strategy:
    blueGreen:
      activeService: {{ include "web.fullname" . }}-active
      previewService: {{ include "web.fullname" . }}-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          ports:
            - containerPort: 3000
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            httpGet:
              path: /healthz
              port: 3000
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            httpGet:
              path: /healthz
              port: 3000
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "web.fullname" . }}-external-secret
                  key: DATABASE_HOST
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "web.fullname" . }}-external-secret
                  key: DATABASE_PASSWORD
            {{ if .Values.externalSecrets.remoteRef.redisPasswordKey }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "web.fullname" . }}-external-secret
                  key: REDIS_PASSWORD
            {{ end }}
            {{ if and .Values.misskeyCm.meilisearch.enabled .Values.externalSecrets.remoteRef.meiliMasterKeyKey }}
            - name: MEILISEARCH_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "web.fullname" . }}-external-secret
                  key: MEILISEARCH_MASTER_KEY
            {{ end }}
          volumeMounts:
          - mountPath: /misskey/.config
            name: misskey-default-conf-file
      volumes:
        - name: misskey-default-conf-file
          configMap:
            name: misskey-default-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}-active
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}-preview
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
