name: Publish Docker Image(misskey-na2na)

on:
  push:
    branches:
      - misskey-na2na
      - topic/docker-build-optimize
  workflow_dispatch:

env:
  DOCKER_TAG_API_URI: https://registry.hub.docker.com/v2/repositories/na2na/misskey-na2na/tags

jobs:
  Check-image-already-exists:
    name: Check image already exists
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.check_docker_hub.outputs.tag_exists }}
      MISSKEY_VERSION: ${{ steps.check_docker_hub.outputs.MISSKEY_VERSION }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1
      - name: Get current version
        id: get_version
        run: |
          echo "MISSKEY_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
      - name: Check Docker Hub
        id: check_docker_hub
        run: |
          DOCKER_HUB_TAGS=$(curl -s https://registry.hub.docker.com/v2/repositories/na2na/misskey-na2na/tags | jq -r '.results[] | .name')
          if [ $(echo $DOCKER_HUB_TAGS | grep -c $MISSKEY_VERSION) -eq 1 ]; then
            echo "Tag $MISSKEY_VERSION already exists on Docker Hub."
          else
            echo "Tag $MISSKEY_VERSION does not exist on Docker Hub."
            echo "tag_exists=false" >> $GITHUB_OUTPUT
            echo "MISSKEY_VERSION=$MISSKEY_VERSION" >> $GITHUB_OUTPUT
          fi

  Build-and-Push-to-Docker-Hub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    needs: Check-image-already-exists
    env:
      MISSKEY_VERSION: ${{ needs.Check-image-already-exists.outputs.MISSKEY_VERSION }}
    if: ${{ needs.Check-image-already-exists.outputs.tag_exists == 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare for build
        id: prepare-for-build
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Cache Docker Build Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: docker-build-cache-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            docker-build-cache-${{ github.ref }}
            docker-build-cache-
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
          docker buildx bake \
              -f 'infra/web/image-bake.hcl' \
              --builder="${{ steps.buildx.outputs.name }}" \
              --set='web.tags=na2na/misskey-na2na:${{ steps.prepare-for-build.outputs.sha_short }}' \
              --set='web.tags=na2na/misskey-na2na:${{ needs.Check-image-already-exists.outputs.MISSKEY_VERSION }}' \
              --push
