name: Publish Docker Image(misskey-na2na)

on:
  pull_request:
    branches:
      - misskey-na2na-deploy
    types: [closed]
  push:
    branches:
      - misskey-na2na
  workflow_dispatch:

env:
  DOCKER_TAG_API_URI: https://registry.hub.docker.com/v2/repositories/na2na/misskey-na2na/tags

jobs:
  Check-image-already-exists:
    name: Check image already exists
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.check_docker_hub.outputs.tag_exists }}
      MISSKEY_VERSION: ${{ env.MISSKEY_VERSION }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.5.0
      - name: Get current version
        id: get_version
        run: |
          echo "MISSKEY_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
      - name: Check Docker Hub
        id: check_docker_hub
        run: |
          DOCKER_HUB_TAGS=$(curl -s https://registry.hub.docker.com/v2/repositories/na2na/misskey-na2na/tags | jq -r '.results[] | .name')
          if [ $(echo $DOCKER_HUB_TAGS | grep -c $MISSKEY_VERSION) -eq 1 ]; then
            echo "Tag $MISSKEY_VERSION already exists on Docker Hub."
          else
            echo "Tag $MISSKEY_VERSION does not exist on Docker Hub."
            echo "tag_exists=false" >> $GITHUB_OUTPUT
            echo "MISSKEY_VERSION=$MISSKEY_VERSION" >> $GITHUB_ENV
          fi

  Build-and-Push-to-Docker-Hub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    needs: Check-image-already-exists
    env:
      MISSKEY_VERSION: ${{ needs.Check-image-already-exists.outputs.MISSKEY_VERSION }}
    if: ${{ needs.Check-image-already-exists.outputs.tag_exists == 'false' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.5.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          platforms: linux/amd64,linux/arm64
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          provenance: false
          tags: |
            na2na/misskey-na2na:release
            na2na/misskey-na2na:${{ env.MISSKEY_VERSION }}
          labels: |
            dev.na2na.misskey-na2na.version=${{ env.MISSKEY_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
